config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :episodes do
    resources :comments
  end

  root 'episodes#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :episode

  validates :body, presence: true
  validates :user, presence: true
  validates :product, presence: true
  validates :rating, numericality: { only_integer: true }
end

app/models/episode.rb
class Episode < ActiveRecord::Base
	belongs_to :user
	has_many :comments

	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |episode|
				csv << episode.attributes.values_at(*column_names)
			end
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :episodes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@episode = Episode.find(params[:episode_id])
		@comment = @episode.comments.new(comment_params)
		@comment.user = current_user

		respond_to do |format|
	      if @comment.save
	        format.html { redirect_to @episode, notice: 'Review was created successfully.' }
	        format.json { render :show, status: :created, location: @episode }
	        format.js
	      else
	        format.html { redirect_to @episode, alert: 'Review was not saved successfully.' }
	        format.json { render json: @comment.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def destroy
		@comment = Comment.find(params[:id])
		episode = @comment.episode
		@comment.destroy
		redirect_to episode
	end

	private

		def comment_params
			params.require(:comment).permit(:user_id, :body, :rating)
		end

end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all
    respond_to do |format|
      format.html
      format.csv { send_data text: @episodes.to_csv }
      # For excel exporting
      format.xls # { send_data @episodes.to_csv(col_sep: "\t") }
    end
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
    @comments = @episode.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:name, :description, :status_type, :image_url)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/episodes/_comments.html.erb
<div class="episode-reviews">
	<% @comments.each do |comment| %>
		<div class="row">
			<hr>
			<p><%= comment.user.first_name %><br><small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
			<div class="rated" data-score="<%= comment.rating %>"></div>
			<% if signed_in? && current_user.admin? %> 
				<%= link_to 'Destroy', episode_comment_path(@episode, comment), method: :delete, data: { confirm: 'Are you sure?' } %> 
			<% end %>
			<p><%= comment.body %></p>
		</div><!-- Row -->
	<% end %>
</div><!-- episode-reviews -->

<%= will_paginate @comments %>

app/views/episodes/_form.html.erb
<%= form_for(@episode) do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <!-- Static select menu in form -->
  <div class="control-group">
    <%= f.label "Status", class: 'control-label' %>
    <div class="controls">
      <%= f.select(:status_type, options_for_select([['PAID', 'PAID'], ['PENDING', 'PENDING']]), { include_blank: true }) %>
    </div>
  </div><!-- End of static select menu -->

  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episodes/_new_comment.html.erb
<% if signed_in? %>
	<h4>Add a Review</h4>
	<%= form_for([@episode, @episode.comments.build]) do |f| %>
		<p>
			<%= f.label :body, "Comments" %><br>
			<%= f.text_area :body %>
		</p>
		<!-- Raty plugin for rating -->
		<p><div class="rating"></div> </p>
		<!-- <p>
			<%= f.label :rating %><br>
			<%= f.text_field :rating, class: "rating" %><br>
		</p> -->
		<p>
			<%= f.submit "Submit" %>
		</p>
	<% end %>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form' %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Episodes</h1>

<p>
  Download:
  <%= link_to "CSV", episodes_path(format: "csv") %>
  <%= link_to "Excel", episodes_path(format: "xls") %>
</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Status</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= episode.name %></td>
        <td><%= truncate(episode.description, :length => 25) %></td>
        <td><%= episode.status_type %></td>
        <td><%= image_tag(episode.image_url, width: "70") %></td>
        <td><%= link_to 'Show', episode %></td>
        <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
        <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Description</Data></Cell>
        <Cell><Data ss:Type="String">Links</Data></Cell>
      </Row>
    <% @episodes.each do |episode| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= episode.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= episode.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= episode.description %></Data></Cell>
        <Cell><Data ss:Type="String"><%= episode.image_url %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/episodes/index.xls_OLD.erb
<!-- This is to format the Excel like a table -->
<table border="1">
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th>Description</th>
		<th>Image Link</th>
		<!-- <th>Created at</th> -->
		<!-- <th>Updated at</th> -->
	</tr>
	<% @episodes.each do |episode| %>
		<tr>
			<td><%= episode.id %></td>
			<td><%= episode.name %></td>
			<td><%= episode.description %></td>
			<td><%= episode.image_url %></td>
			<!-- <td><%= episode.created_at %></td> -->
			<!-- <td><%= episode.updated_at %></td> -->
		</tr>
	<% end %>
</table>

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form' %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<%= link_to 'Edit', edit_episode_path(@episode) %> |
<%= link_to 'Back', episodes_path %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @episode.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @episode.description %>
</p>

<p>
  <strong>Image url:</strong><br>
  <%= image_tag(@episode.image_url, width: "350") %>
</p>


<%= render 'new_comment' %>

<%= render 'comments' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <header>
    	<nav class="navbar navbar-default">
    		<div class="container-fluid">
    			<div class="navbar-header">
    				<a class="navbar-brand" href="/">Test Site</a>
    			</div><!-- navbar-header -->
    			<ul class="nav navbar-nav navbar-right">
    				<li><a href="/">Articles</a></li>
    				<li><a href="/users">Users</a></li>
    				<li><% if user_signed_in? %>
    						<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
    					<% else %>
    						<%= link_to('Login', new_user_session_path) %>
    					<% end %>
    				</li><!-- User Signed in -->
    			</ul>
    		</div><!-- container-fluid -->
    	</nav>
    </header>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>